name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.db_password }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Update apt-get
      run: |
        apt update
        apt install sudo
    - name: Verify MySQL connection from host
      run: |
        apt-get install -y mysql-client
        mysql --host mydb -uroot -p${{ secrets.db_password }} -e "SHOW DATABASES"
    - name: Install dependencies
      run: shards install
    - uses: 1arp/create-a-file-action@0.2
      with:
        file: 'config.yml'
        content: |
          database:
            default: &default
              host: mydb
              user: root
              password: ${{ secrets.db_password }}
              adapter: mysql
            development:
              <<: *default
              db: abhook_api_db_dev
            test:
              <<: *default
              db: abhook_api_db_test
            production:
              <<: *default
              db: abhook_api_db_prod
    - name: Setup database
      env:
        CRYSTAL_ENV: test
      run: make sam db:setup
    - name: Run tests
      run: crystal spec
